#!/bin/bash
echo ""
echo -e '             \E[37;42mWelcome to RenKnights  preconfigured server!'"\033[1m\033[0m"
echo ""
echo "If you are a Renegades Knight customer, you can obtain premium help at https://renknight.com"
echo "Community support available at https://renknight.com/faq"
